yacapp/urls.py
from django.conf.urls.defaults import patterns, url

from yacapp import views

urlpatterns = patterns('',
    url(r'^delete/', views.comment_delete, name='comment-delete'),
    url(r'^edit/', views.comment_edit, name='comment-edit'),
    url(r'^post/', views.comment_post, name='comment-post'),
)

yacapp/models.py
from django.db import models
from django.contrib.auth.models import User

from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic

class Comment(models.Model):

    user = models.ForeignKey(User)
    parent = models.ForeignKey('Comment', null=True)

    title = models.TextField()
    level = models.IntegerField(default=1)
    text = models.TextField()
    deleted = models.DateTimeField(null=True)

    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    content_object = generic.GenericForeignKey('content_type', 'object_id')

    modified = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

yacapp/views.py
from django.utils.timesince import timesince
from django.utils.html import escape
from django.db import models as django_models
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.template import loader, RequestContext, Context
from django.utils import html

import datetime
import json
import logging
import time

from dakku.ajax import AjaxResponse
from dakku import log

from yacapp import signals
from yacapp import models

import logging

logger = logging.getLogger(__name__)

class GetContentObjectError(Exception):
    pass

# Taken from django/contrib/comments/views/comments.py:post_comment
def get_content_object(content_type, object_pk):

    # Look up the object we're trying to comment about
    if content_type is None or object_pk is None:
        raise GetContentObjectError('Missing content_type or object_pk field.')
    try:
        model = django_models.get_model(*content_type.split('.', 1))
        content_object = model._default_manager.using(None).get(pk=object_pk)
    except TypeError:
        raise GetContentObjectError('Invalid content_type value: %r' % escape(content_type))
    except AttributeError:
        raise GetContentObjectError('The given content-type %r does not resolve to a valid model.' % \
                escape(content_type))
    except ObjectDoesNotExist:
        raise GetContentObjectError('No object matching content-type %r and object PK %r exists.' % \
                (escape(content_type), escape(object_pk)))
    except (ValueError, ValidationError), e:
        raise GetContentObjectError(
            'Attempting go get content-type %r and object PK %r exists raised %s' % \
                (escape(content_type), escape(object_pk), e.__class__.__name__))
    return content_object

def comment_post(request, template='comment.html'):

    if not request.user.is_authenticated():
        return AjaxResponse(False, error='User must be authenticated')

    if not request.POST:
        return AjaxResponse(False, error='Post required')

    comment_text = html.escape(request.POST['text'])
    if len(comment_text) == 0:
        return AjaxResponse(False, error='Comment must contain some text %s' %
                (len(comment_text)))

    content_object = get_content_object(
        request.POST.get('content_type'),
        request.POST.get('object_pk'))

    comment = models.Comment(
        user=request.user,
        content_object=content_object,
        text=comment_text)

    if 'title' in request.POST:
        comment.title = request.POST['title']
    if 'parent_id' in request.POST:
        comment.parent = models.Comment.objects.get(
                pk=int(request.POST['parent_id'].replace('comment-', '')))
        comment.level = comment.parent.level + 1

    comment.save()

    content_object.comment_count += 1
    content_object.save()

    logger.info('%s added a comment' % (request.user))

    signals.comment_was_posted.send(
        sender=comment.__class__,
        comment=comment,
        request=request,
    )

    return AjaxResponse(True,
            comment=loader.render_to_string(template, {
                'comment':comment,
            }, context_instance=RequestContext(request)),
            comment_count=content_object.comment_count)

@log.logger()
def comment_edit(request, template='include/comment.html', logger=None):

    if not request.user.is_authenticated():
        return AjaxResponse(False, error='User must be authenticated')

    if not request.POST:
        return AjaxResponse(False, error='Post required')

    try:
        comment = models.Comment.objects.get(
            id=request.POST['comment_id'].replace('comment-', ''))
    except models.Comment.DoesNotExist as e:
        return AjaxResponse(False, error=str(e))

    try:
        text = request.POST['text']
    except MultiValueDictKeyError as e:
        logger.error(str(e))
        return AjaxResponse(False, error=str(e))

    if request.user != comment.user:
        logger.info('Unauthorized comment edit by ' % (request.user))
        return AjaxResponse(False, error='Not authorizied')

    comment.text = text
    comment.save()

    logger.info('%s edited a comment' % (request.user))

    return AjaxResponse(True, text=comment.text)

@log.logger()
def comment_delete(request, logger=None):

    if not request.user.is_authenticated():
        return AjaxResponse(False, error='User must be authenticated')

    content_object = get_content_object(
        request.POST.get('content_type'),
        request.POST.get('object_pk'))

    try:
        comment = models.Comment.objects.get(
            id=request.POST['comment_id'].replace('comment-', ''))
    except models.Comment.DoesNotExist as e:
        return AjaxResponse(False, error=str(e))

    if request.user != comment.user:
        logger.info('Unauthorized comment deletion by ' % (request.user))
        return AjaxResponse(False, error='Not authorizied')

    comment.deleted = datetime.datetime.now()
    comment.save()

    content_object.comment_count -= 1
    content_object.save()

    logger.info('%s deleted a comment' % (request.user))
    return AjaxResponse(True,
            comment_count=content_object.comment_count)

yacapp/templates/comment.html
<div class="comment level-{{ comment.level }}" id="comment-{{ comment.id }}">
  <p id="p-{{ comment.id }}">{{ comment.text|safe }}</p>
  <ul>
    <li>by {{ comment.user.get_profile.display_name }}</li>
    <li>{{ comment.created|timesince }} ago</li>
  </ul>

  <ul class="right">
    {% if request.user == comment.user %}
    <li>
      <a id="edit-{{ comment.id }}" onclick="comment_edit(this, event)" href="#">Edit</a>
    </li>
    <li>
      <a id="delete-{{ comment.id }}" onclick="comment_delete(this, event)" href="#">Delete</a>
    </li>
    {% else %}
    <li>
      <a id="reply-{{ comment.id }}" onclick="comment_reply(this, event)" href="#">Reply</a>
    </li>
    {% endif %}
  </ul>

  {% if replies %}
    <div class="replies">
      {{ replies|safe }}
    </div>
  {% endif %}
</div>

yacapp/templates/comments.html
{% load yacapp_tags %}

<div>
  {% with comment_count=post.comment_count %}
  <h2 class="comment-count">{{ comment_count }} Comment{{ comment_count|pluralize }}</h2>
  <hr/>
  {% endwith %}

  <div class="comments">
    {% comments for post with "include/comment.html" %}
  </div>

  <div class="comment-edit" title="Edit comment">
    <form action="#">
      <input type="hidden" id="comment_id"></input>
      <div class="fieldWrapper lastFieldWrapper">
        <label for="id_edit">Edit:</label>
        <textarea id="id_edit"></textarea>
      </div>
      <button class="edit-save" type="submit">Save</button>
    </form>
  </div>

  <div class="comment-reply" title="Reply to comment">
    <p class="comment-text"></p>
    <form action="#">
      <input type="hidden" id="parent_id"></input>
      <div class="fieldWrapper lastFieldWrapper">
        <label for="id_reply">Reply:</label>
        <textarea id="id_reply"></textarea>
      </div>
      <button class="post-reply" type="submit">Save</button>
    </form>
  </div>

  <div class="settings-dialog" title="Change Settings">
    <form action="#">
      <div class="fieldWrapper lastFieldWrapper">
        <label for="id_display">Display Name:</label>
        <input type="text" id="id_display" value="{{ request.user.get_profile.display_name }}"></input>
      </div>
      <div class="fieldWrapper lastFieldWrapper">
        <label for="id_email">Email:</label>
        <input type="text" id="id_email" value="{{ request.user.email }}"></input>
      </div>
      <div class="fieldWrapper">
        <label for="id_email">Receive email on comment replies:</label>

        <input type="checkbox" id="id_subscribed" checked="{{ request.user.get_profile.subscribed }}"></input>
      </div>
      <button class="save-settings" type="submit">Save</button>
    </form>
  </div>

  <div class="error"></div>

  {% if request.user.is_authenticated %}
  <div class="comment-form">
    <form action="#">

        <label class="comment-label" for="id_text">
        Comment as <span class="display-name">{{ request.user.get_profile.display_name }}</span> (<a class="change-settings" href="#">change</a>):</label>

        <textarea id="id_text"></textarea>
      <button class="post-button" type="submit">Post</button>
    </form>
  </div>
  {% else %}
  <div class="login-form">
    <h2>Login to comment:</h2> 
    <ul>
      <li>
      <a href="{% url socialauth_begin 'twitter' %}?next={% url post-view post.slug %}"><img src="{{ STATIC_URL }}auth/twitter_32.png"/></a>
      </li>
      <li>
      <a href="{% url socialauth_begin 'google' %}?next={% url post-view post.slug %}"><img src="{{ STATIC_URL }}auth/google_32.png"/></a>
      </li>
      <li>
      <a href="{% url socialauth_begin 'github' %}?next={% url post-view post.slug %}"><img src="{{ STATIC_URL }}auth/github_32.png"/></a>
      </li>
      <li>
      <a href="{% url socialauth_begin 'linkedin' %}?next={% url post-view post.slug %}"><img src="{{ STATIC_URL }}auth/linkedin_32.png"/></a>
      </li>
    </ul>
  </div>
  {% endif %}


</div>